# Working with numpy

First things first, we need to import the numpy.

In [1]:
import numpy as np

let us create a normal list of numbers

In [5]:
ages = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
print(ages)
type(ages) #just to show you that this is a list :)

[10, 50, 21, 78, 85, 98, 52, 45, 36, 25, 11, 8, 5, 79]


list

chnaging the list to numpy array - the fun begins!

In [4]:
ages_array = np.array(ages)
print(ages_array)
type(ages_array) #just to show you that this is now a numpy array!

[10 50 21 78 85 98 52 45 36 25 11  8  5 79]


numpy.ndarray

ndarray means n dimensional array. <br>
we can see the size and shape of the array too.<br>
size = number of elements (ages in this case) <br>
shape = dimension of the array <br>

*once an array is created in numpy, its size cannot be changed*

In [13]:
size = ages_array.size
shape = ages_array.shape
print(f'Size = {size} \nType of the above output = {type(size)} \nShape = {shape} \nType of the above output = {type(shape)} ')

Size = 14 
Type of the above output = <class 'int'> 
Shape = (14,) 
Type of the above output = <class 'tuple'> 


In [10]:
# size can also be found with 'len' method which gives output in integer
size_len = len(ages_array)
print(size_len)

14


Reshaping the array

In [26]:
ages1 = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
ages2 = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
both = ages1 + ages2
both = np.array(both) 
reshaped = both.reshape((2,14))
print(reshaped) # now the array is 2D with each dimension having 14 elements

[[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]


Indexing in numpy arrays

In [29]:
# indexing in the normal numpy array
print(f'The normal numpy array we created = {ages_array2}')
print(f'Normal numpy array 5th index = {ages_array[4]}')

The normal numpy array we created = [10 50 21 78 85 98 52 45 36 25 11  8  5 79]
Normal numpy array 5th index = 85


In [31]:
# indexing in the reshaped numpy array
print(f'The normal numpy array we created = {reshaped}')
print(f'Normal numpy array 5th index = {reshaped[1,4]}')

The normal numpy array we created = [[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]
Normal numpy array 5th index = 85
