# Working with numpy

**First things first, we need to import the numpy.**

In [6]:
import numpy as np

**let us create a normal list of numbers**

In [ ]:
ages = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
print(ages)
type(ages) #just to show you that this is a list :)

[10, 50, 21, 78, 85, 98, 52, 45, 36, 25, 11, 8, 5, 79]


list

**chnaging the list to numpy array - the fun begins!**

In [ ]:
ages_array = np.array(ages)
print(ages_array)
type(ages_array) #just to show you that this is now a numpy array!

[10 50 21 78 85 98 52 45 36 25 11  8  5 79]


numpy.ndarray

**ndarray means n dimensional array.** <br>
**we can see the size and shape of the array too.**<br>
**size = number of elements (ages in this case)** <br>
**shape = dimension of the array** <br>

*once an array is created in numpy, its size cannot be changed* 

In [ ]:
size = ages_array.size
shape = ages_array.shape
print(f'Size = {size} \nType of the above output = {type(size)} \nShape = {shape} \nType of the above output = {type(shape)} ')

Size = 14 
Type of the above output = <class 'int'> 
Shape = (14,) 
Type of the above output = <class 'tuple'> 


In [ ]:
# size can also be found with 'len' method which gives output in integer
size_len = len(ages_array)
print(size_len)

14


**Reshaping the array**

In [ ]:
ages1 = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
ages2 = [10,50,21,78,85,98,52,45,36,25,11,8,5,79]
both = ages1 + ages2
both = np.array(both) 
reshaped = both.reshape((2,14))
print(reshaped) # now the array is 2D with each dimension having 14 elements

[[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]


**Indexing in numpy arrays** <br>
[Check out this website!](https://numpy.org/doc/stable/reference/arrays.indexing.html)


In [ ]:
# indexing in the normal numpy array
print(f'The normal numpy array we created = {ages_array}')
print(f'Normal numpy array 5th index = {ages_array[4]}')

The normal numpy array we created = [10 50 21 78 85 98 52 45 36 25 11  8  5 79]
Normal numpy array 5th index = 85


In [ ]:
# indexing in the reshaped numpy array
print(f'The normal numpy array we created = {reshaped}')
print(f'Normal numpy array 5th index = {reshaped[1,4]}')

The normal numpy array we created = [[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]
Normal numpy array 5th index = 85


**Slicing numpy arrays**


In [ ]:
# general form of the syntax : arr[start:stop:step]
print(f'The array we are working on : \n{reshaped}')
print(f'The first three elements from the first row = {reshaped[0,0:3]}')
# alternative of the above code
print(f'The first three elements from the first row [alternative] = {reshaped[0,:3]}') #since we are starting from index 0 itself, we can omit the 0
print(f'The entire fourth column of the 2D array = {reshaped[:,3]}')

The array we are working on : 
[[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]
The first three elements from the first row = [10 50 21]
The first three elements from the first row [alternative] = [10 50 21]
The entire fourth column of the 2D array = [78 78]


**Value assignment** <br>
[click here for more](https://numpy.org/doc/stable/reference/arrays.indexing.html)

In [ ]:
test = reshaped
print(f'The array initially: \n{test}')
print(f'Initial Value of 1st array 4th column {test[0,3]}')
test[0,3] = 1234
print(f'New Value of 1st array 4th column {test[0,3]}')
print(f'The array now: \n{test}')

The array initially: 
[[10 50 21 78 85 98 52 45 36 25 11  8  5 79]
 [10 50 21 78 85 98 52 45 36 25 11  8  5 79]]
Initial Value of 1st array 4th column 78
New Value of 1st array 4th column 1234
The array now: 
[[  10   50   21 1234   85   98   52   45   36   25   11    8    5   79]
 [  10   50   21   78   85   98   52   45   36   25   11    8    5   79]]


**Assign single value to one whole array**

In [ ]:
print(f'The array initially: \n{test}')
#here is the fun part!
test[0,:] = 5678
print(f'The array now: \n{test}')

The array initially: 
[[  10   50   21 1234   85   98   52   45   36   25   11    8    5   79]
 [  10   50   21   78   85   98   52   45   36   25   11    8    5   79]]
The array now: 
[[5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678]
 [  10   50   21   78   85   98   52   45   36   25   11    8    5   79]]


**Assigning values to subset to the array**

In [ ]:
print(f'The array initially: \n{test}')
test[:5, :5] = 1010
print(f'The array now: \n{test}')

The array initially: 
[[5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678 5678]
 [  10   50   21   78   85   98   52   45   36   25   11    8    5   79]]
The array now: 
[[1010 1010 1010 1010 1010 5678 5678 5678 5678 5678 5678 5678 5678 5678]
 [1010 1010 1010 1010 1010   98   52   45   36   25   11    8    5   79]]


**Stacking arrays** <br>
[documentation](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)

In [13]:
#Join a sequence of arrays along a new axis.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(f'Basic Stacking : \n {np.stack((a, b))}')
print(f'Axis = -1 : \n {np.stack((a, b), axis = -1)}')
print(f'Axis = -2 : \n {np.stack((a, b), axis = -2)}')
print(f'Axis = -3 : \nGives error : axis -3 is out of bounds for array of dimension 2')

Basic Stacking : 
 [[1 2 3]
 [2 3 4]]
Axis = -1 : 
 [[1 2]
 [2 3]
 [3 4]]
Axis = -2 : 
 [[1 2 3]
 [2 3 4]]
Axis = -3 : 
Gives error : axis -3 is out of bounds for array of dimension 2
