## Working with Numpy 
Documentation : https://numpy.org/doc/ (Trust me, it saves you a lot of effort)<br>
<p>NumPy is the fundamental package needed for scientific computing with Python. This package contains:</p>
<ul class="simple">
<li>
<p>a powerful N-dimensional&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/arrays.html#arrays"><span class="std std-ref">array object</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs"><span class="std std-ref">(broadcasting) functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.linalg.html#routines-linalg"><span class="std std-ref">linear algebra functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.fft.html#routines-fft"><span class="std std-ref">Fourier transforms</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/random/index.html#numpyrandom"><span class="std std-ref">random number capabilities</span></a></p>
</li>
<li>
<p>tools for integrating Fortran code</p>
</li>
<li>
<p>tools for integrating C/C++ code</p>
</li>
</ul>
<p>Besides its obvious scientific uses,&nbsp;<em>NumPy</em>&nbsp;can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows&nbsp;<em>NumPy</em>&nbsp;to seamlessly and speedily integrate with a wide variety of databases.</p>
<p>NumPy is a successor for two earlier scientific Python libraries: Numeric and Numarray.</p>

In [1]:
#import numpy library first
import numpy as np

![](https://pics.me.me/1-import-numpy-1-import-numpy-as-np-there-is-31232276.png)

## DataTypes and Attributes

**The predominant datatype in numpy is "numpy array"**

In [2]:
ar = np.array([4,5,6])
ar

array([4, 5, 6])

In [3]:
ar.dtype #it is in integer

dtype('int32')

In [4]:
ar2 = np.array([[3,2,1],[6,5,4]])
ar2

array([[3, 2, 1],
       [6, 5, 4]])

In [5]:
ar3 = np.array([[[3,2,1],[6,5,4],[9.3,8.2,7.1]],
              [[3,2,1],[6,5,4],[9,5,1]]])
ar3

array([[[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9.3, 8.2, 7.1]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9. , 5. , 1. ]]])

In [6]:
ar3.dtype #it is in float

dtype('float64')

Now here is the explanation for what just happened!
![](https://udemy-images.s3.amazonaws.com/redactor/raw/2020-01-28_03-56-32-433698fdb6cb595d61a490062cd00619.png)

Just in case if it helps,<br>
Formula for shape of an array = R X C [R=row, C=column] <br>
Axes for multidimensional arrays :<br>
Axis 0 = Rows<br>
Axis 1 = Columns<br>
Axis n = Beyond rows and columns (You may think of it as the z axis)


In [7]:
#dimensions
ar.ndim, ar2.ndim, ar3.ndim

(1, 2, 3)

In [8]:
#size or number of elements in each array
ar.size, ar2.size, ar3.size

(3, 6, 18)

In [9]:
#types of data 
type(ar), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

**Numpy array to Pandas dataframe**


In [10]:
import pandas as pd
pd.DataFrame(ar)

0
0  4
1  5
2  6

In [11]:
pd.DataFrame(ar2)

0  1  2
0  3  2  1
1  6  5  4

**pd.DataFrame(ar3)** -------- this gives an error<br>
ValueError: Must pass 2-d input, <br>ie, A 3D array cannot be described in form of a dataframe

![](https://www.thecoderpedia.com/wp-content/uploads/2020/06/Programming-Memes.jpg?x78009)

## Creating numpy arrays

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

<p><code class="sig-prename descclassname">numpy.</code><code class="sig-name descname"><span class="highlighted">ones</span></code><span class="sig-paren">(</span><em class="sig-param">shape</em>,&nbsp;<em class="sig-param">dtype=None</em>,&nbsp;<em class="sig-param">order='C'</em><span class="sig-paren">)</span></p>
<p>Return a new array of given shape and type, filled with&nbsp;<span class="highlighted">ones</span>.</p>
<p>&nbsp;</p>

In [13]:
ones.dtype

dtype('float64')

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

<p>numpy.zeros(shape, dtype=float, order='C')<br> Return a new array of given shape and type, filled with zeros.</p>

In [15]:
zeros.dtype

dtype('float64')

In [16]:
#arange
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

<p><code class="sig-prename descclassname">numpy.</code><code class="sig-name descname">a<span class="highlighted">range</span></code><span class="sig-paren">(</span><span class="optional">[</span><em class="sig-param">start</em>,&nbsp;<span class="optional">]</span><em class="sig-param">stop</em>,&nbsp;<span class="optional">[</span><em class="sig-param">step</em>,&nbsp;<span class="optional">]</span><em class="sig-param">dtype=None</em><span class="sig-paren">)</span></p>
<p>Return evenly spaced values within a given interval.</p>
<p>Values are generated within the half-open interval&nbsp;<code class="docutils literal notranslate"><span class="pre">[start,</span>&nbsp;<span class="pre">stop)</span></code>&nbsp;(in other words, the interval including&nbsp;<em class="xref py py-obj">start</em>&nbsp;but excluding&nbsp;<em class="xref py py-obj">stop</em>). For integer arguments the function is equivalent to the Python built-in&nbsp;<em class="xref py py-obj"><span class="highlighted">range</span></em>&nbsp;function, but returns an ndarray rather than a list.</p>
<p>When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use&nbsp;<a class="reference internal" title="numpy.linspace" href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.linspace</span></code></a>&nbsp;for these cases.</p>
<p>&nbsp;</p>

In [17]:
#creating random arrays with - random.randint
np.random.randint(1,100,size=(10,10))
#all numbers will show up in the array but in random oder

array([[88, 95, 32,  1, 29, 81,  4, 63, 88, 17],
       [14, 36,  5, 75,  7, 37, 40, 45, 98,  8],
       [36,  3, 94, 58, 12, 54, 67, 29, 75, 22],
       [54, 38, 75, 69, 13, 80,  4, 55, 78, 44],
       [63, 67, 83, 84, 10,  4,  3, 84, 89, 63],
       [77, 29, 52, 71,  2, 74, 44, 85, 50, 71],
       [12,  2, 93, 29, 55, 98, 39, 28, 21,  4],
       [71, 87, 80, 21, 94, 27, 81, 15, 70, 48],
       [30, 91, 51, 15, 49, 46, 23, 23, 60, 39],
       [68, 59, 38, 82, 99, 39, 82, 69, 97, 16]])

<h6>numpy.<span class="highlighted">random</span>.<span class="highlighted">randint</span></h6>
<dl class="function">
<dt id="numpy.random.randint"><code class="sig-prename descclassname">numpy.<span class="highlighted">random</span>.</code><code class="sig-name descname"><span class="highlighted">randint</span></code><span class="sig-paren">(</span><em class="sig-param">low</em>,&nbsp;<em class="sig-param">high=None</em>,&nbsp;<em class="sig-param">size=None</em>,&nbsp;<em class="sig-param">dtype=int</em><span class="sig-paren">)</span></dt>
<dd>
<p>Return&nbsp;<span class="highlighted">random</span>&nbsp;integers from&nbsp;<em class="xref py py-obj">low</em>&nbsp;(inclusive) to&nbsp;<em class="xref py py-obj">high</em>&nbsp;(exclusive).</p>
<p>Return&nbsp;<span class="highlighted">random</span>&nbsp;integers from the &ldquo;discrete uniform&rdquo; distribution of the specified dtype in the &ldquo;half-open&rdquo; interval [<em class="xref py py-obj">low</em>,&nbsp;<em class="xref py py-obj">high</em>). If&nbsp;<em class="xref py py-obj">high</em>&nbsp;is None (the default), then results are from [0,&nbsp;<em class="xref py py-obj">low</em>).</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>New code should use the&nbsp;<code class="docutils literal notranslate"><span class="pre">integers</span></code>&nbsp;method of a&nbsp;<code class="docutils literal notranslate"><span class="pre">default_rng()</span></code>&nbsp;instance instead; see&nbsp;<em class="xref py py-obj"><span class="highlighted">random</span>-quick-start</em>.</p>
</div>
</dd>
</dl>

In [18]:
#another example
np.random.rand(1,100)

array([[0.18745064, 0.84536979, 0.24812191, 0.64591071, 0.27794165,
        0.40850771, 0.38359328, 0.87287381, 0.67829047, 0.82598528,
        0.59648965, 0.99683861, 0.05140911, 0.01262209, 0.7102368 ,
        0.02656911, 0.52620486, 0.46986666, 0.42582429, 0.1360686 ,
        0.95708653, 0.54795478, 0.29664206, 0.8787007 , 0.16490465,
        0.07152172, 0.66074912, 0.25528657, 0.62435169, 0.06812731,
        0.0609757 , 0.19815349, 0.71589455, 0.7137231 , 0.18016312,
        0.37013126, 0.99378372, 0.15353715, 0.61455641, 0.18896903,
        0.76008736, 0.48318616, 0.16471749, 0.64212004, 0.30278513,
        0.44522197, 0.42909182, 0.60122743, 0.76077281, 0.9696173 ,
        0.85592423, 0.88149242, 0.20694246, 0.86777572, 0.01638645,
        0.57169317, 0.4670084 , 0.82346917, 0.80170852, 0.9770457 ,
        0.57285162, 0.47044922, 0.27452576, 0.83068365, 0.00451389,
        0.3801474 , 0.20819296, 0.71633706, 0.94953491, 0.30972555,
        0.75071221, 0.19620101, 0.68444046, 0.46

In [19]:
#numpy seed = gives pseudo random numbers
np.random.seed(seed=0)
rar = np.random.randint(10,size=(5,3))
rar

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

<p><code class="sig-prename descclassname">numpy.random.</code><code class="sig-name descname"><span class="highlighted">seed</span></code><span class="sig-paren">(</span><em class="sig-param">self</em>,&nbsp;<em class="sig-param"><span class="highlighted">seed</span>=None</em><span class="sig-paren">)</span></p>
<p>Re<span class="highlighted">seed</span>&nbsp;a legacy MT19937 BitGenerator</p>
<p>&nbsp;</p>
<br><br><br><br>

![](https://i.imgur.com/ZYvo0BK.jpg)

## Viewing arrays and matrices

In [25]:
#let us consider the following array
ar = np.array([[1,2,3],[3,2,1],[4,5,6],[6,5,4],[7,8,9],[9,8,7]])
ar

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [6, 5, 4],
       [7, 8, 9],
       [9, 8, 7]])

In [26]:
#find unique elements in a numpy array
np.unique(ar)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#access array elements
ar[0]

array([1, 2, 3])

In [29]:
ar[2]

array([4, 5, 6])

In [32]:
ar.shape

(6, 3)

In [33]:
ar.size

18

In [40]:
#let the array now be 
np.random.seed(seed=0) # we need seed so that the numbers in the array dont change in future usage
ar = np.random.randint(1,20,size=(5,5))
ar

array([[13, 16,  1,  4,  4],
       [ 8, 10, 19,  5,  7],
       [13,  2,  7,  8, 15],
       [18,  6, 14,  9, 10],
       [17,  6, 16, 16,  1]])

In [45]:
#shape and dimension
ar.shape, ar.ndim

((5, 5), 2)

In [41]:
#slicing the arrays
ar[:2]
#first 2 rows

array([[13, 16,  1,  4,  4],
       [ 8, 10, 19,  5,  7]])

In [42]:
#slicing the arrays
ar[:2,:1]
#first 2 rows with 1 column

array([[13],
       [ 8]])

In [44]:
#slicing the arrays
ar[:1,:3]
#first 1 row with 3 column data

array([[13, 16,  1]])

![](https://www.google.com/url?sa=i&url=https%3A%2F%2Fimgflip.com%2Fi%2F1bjzfn&psig=AOvVaw3YroJ_qg0gBF9dkgpzWi8F&ust=1597951367550000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjYnZ7_p-sCFQAAAAAdAAAAABAO)

![](https://i.imgflip.com/1bjzfn.jpg)

## Manipulate and compare arrays

In [47]:
#simple addition of arrays
ar + ar

array([[26, 32,  2,  8,  8],
       [16, 20, 38, 10, 14],
       [26,  4, 14, 16, 30],
       [36, 12, 28, 18, 20],
       [34, 12, 32, 32,  2]])