## Working with Numpy 
Documentation : https://numpy.org/doc/ (Trust me, it saves you a lot of effort)<br>
<p>NumPy is the fundamental package needed for scientific computing with Python. This package contains:</p>
<ul class="simple">
<li>
<p>a powerful N-dimensional&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/arrays.html#arrays"><span class="std std-ref">array object</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs"><span class="std std-ref">(broadcasting) functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.linalg.html#routines-linalg"><span class="std std-ref">linear algebra functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.fft.html#routines-fft"><span class="std std-ref">Fourier transforms</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/random/index.html#numpyrandom"><span class="std std-ref">random number capabilities</span></a></p>
</li>
<li>
<p>tools for integrating Fortran code</p>
</li>
<li>
<p>tools for integrating C/C++ code</p>
</li>
</ul>
<p>Besides its obvious scientific uses,&nbsp;<em>NumPy</em>&nbsp;can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows&nbsp;<em>NumPy</em>&nbsp;to seamlessly and speedily integrate with a wide variety of databases.</p>
<p>NumPy is a successor for two earlier scientific Python libraries: Numeric and Numarray.</p>

In [2]:
#import numpy library first
import numpy as np

![](https://pics.me.me/1-import-numpy-1-import-numpy-as-np-there-is-31232276.png)

## DataTypes and Attributes

**The predominant datatype in numpy is "numpy array"**

In [3]:
ar = np.array([4,5,6])
ar

array([4, 5, 6])

In [30]:
ar.dtype #it is in integer

dtype('int32')

In [7]:
ar2 = np.array([[3,2,1],[6,5,4]])
ar2

array([[3, 2, 1],
       [6, 5, 4]])

In [11]:
ar3 = np.array([[[3,2,1],[6,5,4],[9.3,8.2,7.1]],
              [[3,2,1],[6,5,4],[9,5,1]]])
ar3

array([[[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9.3, 8.2, 7.1]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9. , 5. , 1. ]]])

In [31]:
ar3.dtype #it is in float

dtype('float64')

Now here is the explanation for what just happened!
![](https://udemy-images.s3.amazonaws.com/redactor/raw/2020-01-28_03-56-32-433698fdb6cb595d61a490062cd00619.png)

Just in case if it helps,<br>
Formula for shape of an array = R X C [R=row, C=column] <br>
Axes for multidimensional arrays :<br>
Axis 0 = Rows<br>
Axis 1 = Columns<br>
Axis n = Beyond rows and columns (You may think of it as the z axis)


In [17]:
#dimensions
ar.ndim, ar2.ndim, ar3.ndim

(1, 2, 3)

In [19]:
#size or number of elements in each array
ar.size, ar2.size, ar3.size

(3, 6, 18)

In [21]:
#types of data 
type(ar), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

**Numpy array to Pandas dataframe**


In [25]:
import pandas as pd
pd.DataFrame(ar)

0
0  4
1  5
2  6

In [26]:
pd.DataFrame(ar2)

0  1  2
0  3  2  1
1  6  5  4

**pd.DataFrame(ar3)** -------- this gives an error<br>
ValueError: Must pass 2-d input, <br>ie, A 3D array cannot be described in form of a dataframe

![](https://www.thecoderpedia.com/wp-content/uploads/2020/06/Programming-Memes.jpg?x78009)

## Creating numpy arrays

In [35]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

<p><code class="sig-prename descclassname">numpy.</code><code class="sig-name descname"><span class="highlighted">ones</span></code><span class="sig-paren">(</span><em class="sig-param">shape</em>,&nbsp;<em class="sig-param">dtype=None</em>,&nbsp;<em class="sig-param">order='C'</em><span class="sig-paren">)</span></p>
<p>Return a new array of given shape and type, filled with&nbsp;<span class="highlighted">ones</span>.</p>
<p>&nbsp;</p>

In [36]:
ones.dtype

dtype('float64')

In [37]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

<p>numpy.zeros(shape, dtype=float, order='C')<br> Return a new array of given shape and type, filled with zeros.</p>

In [39]:
zeros.dtype

dtype('float64')