## Working with Numpy 
Documentation : https://numpy.org/doc/ (Trust me, it saves you a lot of effort)<br>
<p>NumPy is the fundamental package needed for scientific computing with Python. This package contains:</p>
<ul class="simple">
<li>
<p>a powerful N-dimensional&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/arrays.html#arrays"><span class="std std-ref">array object</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs"><span class="std std-ref">(broadcasting) functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.linalg.html#routines-linalg"><span class="std std-ref">linear algebra functions</span></a></p>
</li>
<li>
<p>basic&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/routines.fft.html#routines-fft"><span class="std std-ref">Fourier transforms</span></a></p>
</li>
<li>
<p>sophisticated&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/reference/random/index.html#numpyrandom"><span class="std std-ref">random number capabilities</span></a></p>
</li>
<li>
<p>tools for integrating Fortran code</p>
</li>
<li>
<p>tools for integrating C/C++ code</p>
</li>
</ul>
<p>Besides its obvious scientific uses,&nbsp;<em>NumPy</em>&nbsp;can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows&nbsp;<em>NumPy</em>&nbsp;to seamlessly and speedily integrate with a wide variety of databases.</p>
<p>NumPy is a successor for two earlier scientific Python libraries: Numeric and Numarray.</p>

In [1]:
#import numpy library first
import numpy as np

![](https://pics.me.me/1-import-numpy-1-import-numpy-as-np-there-is-31232276.png)

## DataTypes and Attributes

**The predominant datatype in numpy is "numpy array"**

In [2]:
ar = np.array([4,5,6])
ar

array([4, 5, 6])

In [3]:
ar.dtype #it is in integer

dtype('int32')

In [4]:
ar2 = np.array([[3,2,1],[6,5,4]])
ar2

array([[3, 2, 1],
       [6, 5, 4]])

In [5]:
ar3 = np.array([[[3,2,1],[6,5,4],[9.3,8.2,7.1]],
              [[3,2,1],[6,5,4],[9,5,1]]])
ar3

array([[[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9.3, 8.2, 7.1]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9. , 5. , 1. ]]])

In [6]:
ar3.dtype #it is in float

dtype('float64')

Now here is the explanation for what just happened!
![](https://udemy-images.s3.amazonaws.com/redactor/raw/2020-01-28_03-56-32-433698fdb6cb595d61a490062cd00619.png)

Just in case if it helps,<br>
Formula for shape of an array = R X C [R=row, C=column] <br>
Axes for multidimensional arrays :<br>
Axis 0 = Rows<br>
Axis 1 = Columns<br>
Axis n = Beyond rows and columns (You may think of it as the z axis)


In [7]:
#dimensions
ar.ndim, ar2.ndim, ar3.ndim

(1, 2, 3)

In [8]:
#size or number of elements in each array
ar.size, ar2.size, ar3.size

(3, 6, 18)

In [9]:
#types of data 
type(ar), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

**Numpy array to Pandas dataframe**


In [10]:
import pandas as pd
pd.DataFrame(ar)

0
0  4
1  5
2  6

In [11]:
pd.DataFrame(ar2)

0  1  2
0  3  2  1
1  6  5  4

**pd.DataFrame(ar3)** -------- this gives an error<br>
ValueError: Must pass 2-d input, <br>ie, A 3D array cannot be described in form of a dataframe

![](https://www.thecoderpedia.com/wp-content/uploads/2020/06/Programming-Memes.jpg?x78009)

## Creating numpy arrays

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

<p><code class="sig-prename descclassname">numpy.</code><code class="sig-name descname"><span class="highlighted">ones</span></code><span class="sig-paren">(</span><em class="sig-param">shape</em>,&nbsp;<em class="sig-param">dtype=None</em>,&nbsp;<em class="sig-param">order='C'</em><span class="sig-paren">)</span></p>
<p>Return a new array of given shape and type, filled with&nbsp;<span class="highlighted">ones</span>.</p>
<p>&nbsp;</p>

In [13]:
ones.dtype

dtype('float64')

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

<p>numpy.zeros(shape, dtype=float, order='C')<br> Return a new array of given shape and type, filled with zeros.</p>

In [15]:
zeros.dtype

dtype('float64')

In [16]:
#arange
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

<p><code class="sig-prename descclassname">numpy.</code><code class="sig-name descname">a<span class="highlighted">range</span></code><span class="sig-paren">(</span><span class="optional">[</span><em class="sig-param">start</em>,&nbsp;<span class="optional">]</span><em class="sig-param">stop</em>,&nbsp;<span class="optional">[</span><em class="sig-param">step</em>,&nbsp;<span class="optional">]</span><em class="sig-param">dtype=None</em><span class="sig-paren">)</span></p>
<p>Return evenly spaced values within a given interval.</p>
<p>Values are generated within the half-open interval&nbsp;<code class="docutils literal notranslate"><span class="pre">[start,</span>&nbsp;<span class="pre">stop)</span></code>&nbsp;(in other words, the interval including&nbsp;<em class="xref py py-obj">start</em>&nbsp;but excluding&nbsp;<em class="xref py py-obj">stop</em>). For integer arguments the function is equivalent to the Python built-in&nbsp;<em class="xref py py-obj"><span class="highlighted">range</span></em>&nbsp;function, but returns an ndarray rather than a list.</p>
<p>When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use&nbsp;<a class="reference internal" title="numpy.linspace" href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.linspace</span></code></a>&nbsp;for these cases.</p>
<p>&nbsp;</p>

In [17]:
#creating random arrays with - random.randint
np.random.randint(1,100,size=(10,10))
#all numbers will show up in the array but in random oder

array([[46, 31, 26, 62, 33, 99, 66, 97, 33, 52],
       [80, 77, 21, 66, 68, 49,  3, 86, 59, 55],
       [78, 26, 42, 22, 82, 88, 35, 56, 85, 90],
       [ 5, 11, 97, 53,  8, 97, 31, 18, 19, 82],
       [53, 10, 75, 93, 39, 43, 90, 75, 88, 60],
       [85, 22,  1, 29, 49, 86, 80, 46, 54, 68],
       [40, 69,  4, 74, 68, 32, 65, 21, 68, 22],
       [24, 68, 78, 68, 22, 49, 21, 65, 14, 34],
       [74, 88, 98, 76,  4, 65, 32,  2, 17, 35],
       [49, 97, 44, 84, 61, 67, 12, 61, 12,  5]])

<h6>numpy.<span class="highlighted">random</span>.<span class="highlighted">randint</span></h6>
<dl class="function">
<dt id="numpy.random.randint"><code class="sig-prename descclassname">numpy.<span class="highlighted">random</span>.</code><code class="sig-name descname"><span class="highlighted">randint</span></code><span class="sig-paren">(</span><em class="sig-param">low</em>,&nbsp;<em class="sig-param">high=None</em>,&nbsp;<em class="sig-param">size=None</em>,&nbsp;<em class="sig-param">dtype=int</em><span class="sig-paren">)</span></dt>
<dd>
<p>Return&nbsp;<span class="highlighted">random</span>&nbsp;integers from&nbsp;<em class="xref py py-obj">low</em>&nbsp;(inclusive) to&nbsp;<em class="xref py py-obj">high</em>&nbsp;(exclusive).</p>
<p>Return&nbsp;<span class="highlighted">random</span>&nbsp;integers from the &ldquo;discrete uniform&rdquo; distribution of the specified dtype in the &ldquo;half-open&rdquo; interval [<em class="xref py py-obj">low</em>,&nbsp;<em class="xref py py-obj">high</em>). If&nbsp;<em class="xref py py-obj">high</em>&nbsp;is None (the default), then results are from [0,&nbsp;<em class="xref py py-obj">low</em>).</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>New code should use the&nbsp;<code class="docutils literal notranslate"><span class="pre">integers</span></code>&nbsp;method of a&nbsp;<code class="docutils literal notranslate"><span class="pre">default_rng()</span></code>&nbsp;instance instead; see&nbsp;<em class="xref py py-obj"><span class="highlighted">random</span>-quick-start</em>.</p>
</div>
</dd>
</dl>

In [18]:
#another example
np.random.rand(1,100)

array([[0.06622416, 0.36481705, 0.43729508, 0.97522086, 0.67944937,
        0.67945117, 0.26280214, 0.67618073, 0.7719471 , 0.9889418 ,
        0.77476261, 0.42536031, 0.26114709, 0.85628319, 0.54893488,
        0.20189206, 0.26667753, 0.68992819, 0.33146041, 0.27811663,
        0.22283201, 0.80035263, 0.13888743, 0.39589432, 0.61947725,
        0.15695288, 0.25766064, 0.57661317, 0.41915   , 0.24237423,
        0.41706614, 0.65728858, 0.25174651, 0.16893713, 0.97878762,
        0.63983466, 0.51541438, 0.23736757, 0.93865576, 0.32085017,
        0.03772224, 0.76386241, 0.86761534, 0.21457062, 0.76051677,
        0.40790425, 0.12542987, 0.08588291, 0.1344389 , 0.54550213,
        0.12059487, 0.07573362, 0.34175898, 0.97776049, 0.27373783,
        0.95916033, 0.85429833, 0.51630973, 0.71886171, 0.27754787,
        0.26616214, 0.44573374, 0.20853194, 0.06764479, 0.74741934,
        0.36524844, 0.34393094, 0.91065017, 0.8807911 , 0.1146227 ,
        0.89635595, 0.20361167, 0.90786584, 0.58

In [19]:
#numpy seed = gives pseudo random numbers
np.random.seed(seed=0)
rar = np.random.randint(10,size=(5,3))
rar

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

<p><code class="sig-prename descclassname">numpy.random.</code><code class="sig-name descname"><span class="highlighted">seed</span></code><span class="sig-paren">(</span><em class="sig-param">self</em>,&nbsp;<em class="sig-param"><span class="highlighted">seed</span>=None</em><span class="sig-paren">)</span></p>
<p>Re<span class="highlighted">seed</span>&nbsp;a legacy MT19937 BitGenerator</p>
<p>&nbsp;</p>
<br><br><br><br>

![](https://i.imgur.com/ZYvo0BK.jpg)

## Viewing arrays and matrices

In [20]:
#let us consider the following array
ar = np.array([[1,2,3],[3,2,1],[4,5,6],[6,5,4],[7,8,9],[9,8,7]])
ar

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [6, 5, 4],
       [7, 8, 9],
       [9, 8, 7]])

In [21]:
#find unique elements in a numpy array
np.unique(ar)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#access array elements
ar[0]

array([1, 2, 3])

In [23]:
ar[2]

array([4, 5, 6])

In [24]:
ar.shape

(6, 3)

In [25]:
ar.size

18

In [26]:
#let the array now be 
np.random.seed(seed=0) # we need seed so that the numbers in the array dont change in future usage
ar = np.random.randint(1,20,size=(5,5))
ar

array([[13, 16,  1,  4,  4],
       [ 8, 10, 19,  5,  7],
       [13,  2,  7,  8, 15],
       [18,  6, 14,  9, 10],
       [17,  6, 16, 16,  1]])

In [27]:
#shape and dimension
ar.shape, ar.ndim

((5, 5), 2)

In [28]:
#slicing the arrays
ar[:2]
#first 2 rows

array([[13, 16,  1,  4,  4],
       [ 8, 10, 19,  5,  7]])

In [29]:
#slicing the arrays
ar[:2,:1]
#first 2 rows with 1 column

array([[13],
       [ 8]])

In [30]:
#slicing the arrays
ar[:1,:3]
#first 1 row with 3 column data

array([[13, 16,  1]])

![](https://www.google.com/url?sa=i&url=https%3A%2F%2Fimgflip.com%2Fi%2F1bjzfn&psig=AOvVaw3YroJ_qg0gBF9dkgpzWi8F&ust=1597951367550000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjYnZ7_p-sCFQAAAAAdAAAAABAO)

![](https://i.imgflip.com/1bjzfn.jpg)

## Manipulate and compare arrays

In [43]:
#our array
ar

array([[13, 16,  1,  4,  4],
       [ 8, 10, 19,  5,  7],
       [13,  2,  7,  8, 15],
       [18,  6, 14,  9, 10],
       [17,  6, 16, 16,  1]])

In [31]:
#simple addition of arrays
ar + ar

array([[26, 32,  2,  8,  8],
       [16, 20, 38, 10, 14],
       [26,  4, 14, 16, 30],
       [36, 12, 28, 18, 20],
       [34, 12, 32, 32,  2]])

In [41]:
ar1 = np.ones((5,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
ar + ar1

array([[14., 17.,  2.,  5.,  5.],
       [ 9., 11., 20.,  6.,  8.],
       [14.,  3.,  8.,  9., 16.],
       [19.,  7., 15., 10., 11.],
       [18.,  7., 17., 17.,  2.]])

In [44]:
#subtraction
ar - ar

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
ar-ar1

array([[12., 15.,  0.,  3.,  3.],
       [ 7.,  9., 18.,  4.,  6.],
       [12.,  1.,  6.,  7., 14.],
       [17.,  5., 13.,  8.,  9.],
       [16.,  5., 15., 15.,  0.]])

In [47]:
#use functions
np.add(ar,ar1)

array([[14., 17.,  2.,  5.,  5.],
       [ 9., 11., 20.,  6.,  8.],
       [14.,  3.,  8.,  9., 16.],
       [19.,  7., 15., 10., 11.],
       [18.,  7., 17., 17.,  2.]])

## Well, let's be honest.
<br>**There are many different functions to explore in NumPy. Best way is to keep the documentation handy and refer to it when we face real life problems!** <br>
Following are a few information directly from the documentation which might be helpful for the time being

<div id="trigonometric-functions" class="section">
<h2>Trigonometric functions</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.sin" href="https://numpy.org/doc/stable/reference/generated/numpy.sin.html#numpy.sin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sin</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Trigonometric sine, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.cos" href="https://numpy.org/doc/stable/reference/generated/numpy.cos.html#numpy.cos"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cos</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Cosine element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.tan" href="https://numpy.org/doc/stable/reference/generated/numpy.tan.html#numpy.tan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">tan</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Compute tangent element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.arcsin" href="https://numpy.org/doc/stable/reference/generated/numpy.arcsin.html#numpy.arcsin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arcsin</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Inverse sine, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.arccos" href="https://numpy.org/doc/stable/reference/generated/numpy.arccos.html#numpy.arccos"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arccos</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Trigonometric inverse cosine, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.arctan" href="https://numpy.org/doc/stable/reference/generated/numpy.arctan.html#numpy.arctan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctan</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Trigonometric inverse tangent, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.hypot" href="https://numpy.org/doc/stable/reference/generated/numpy.hypot.html#numpy.hypot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hypot</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Given the &ldquo;legs&rdquo; of a right triangle, return its hypotenuse.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.arctan2" href="https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html#numpy.arctan2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctan2</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Element-wise arc tangent of&nbsp;<code class="docutils literal notranslate"><span class="pre">x1/x2</span></code>&nbsp;choosing the quadrant correctly.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.degrees" href="https://numpy.org/doc/stable/reference/generated/numpy.degrees.html#numpy.degrees"><code class="xref py py-obj docutils literal notranslate"><span class="pre">degrees</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Convert angles from radians to degrees.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.radians" href="https://numpy.org/doc/stable/reference/generated/numpy.radians.html#numpy.radians"><code class="xref py py-obj docutils literal notranslate"><span class="pre">radians</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Convert angles from degrees to radians.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.unwrap" href="https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html#numpy.unwrap"><code class="xref py py-obj docutils literal notranslate"><span class="pre">unwrap</span></code></a>(p[,&nbsp;discont,&nbsp;axis])</p>
</td>
<td>
<p>Unwrap by changing deltas between values to 2*pi complement.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.deg2rad" href="https://numpy.org/doc/stable/reference/generated/numpy.deg2rad.html#numpy.deg2rad"><code class="xref py py-obj docutils literal notranslate"><span class="pre">deg2rad</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Convert angles from degrees to radians.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.rad2deg" href="https://numpy.org/doc/stable/reference/generated/numpy.rad2deg.html#numpy.rad2deg"><code class="xref py py-obj docutils literal notranslate"><span class="pre">rad2deg</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Convert angles from radians to degrees.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="hyperbolic-functions" class="section">
<h2>Hyperbolic functions</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.sinh" href="https://numpy.org/doc/stable/reference/generated/numpy.sinh.html#numpy.sinh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sinh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Hyperbolic sine, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.cosh" href="https://numpy.org/doc/stable/reference/generated/numpy.cosh.html#numpy.cosh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cosh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Hyperbolic cosine, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.tanh" href="https://numpy.org/doc/stable/reference/generated/numpy.tanh.html#numpy.tanh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">tanh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Compute hyperbolic tangent element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.arcsinh" href="https://numpy.org/doc/stable/reference/generated/numpy.arcsinh.html#numpy.arcsinh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arcsinh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Inverse hyperbolic sine element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.arccosh" href="https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html#numpy.arccosh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arccosh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Inverse hyperbolic cosine, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.arctanh" href="https://numpy.org/doc/stable/reference/generated/numpy.arctanh.html#numpy.arctanh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctanh</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Inverse hyperbolic tangent element-wise.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="rounding" class="section">
<h2>Rounding</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.around" href="https://numpy.org/doc/stable/reference/generated/numpy.around.html#numpy.around"><code class="xref py py-obj docutils literal notranslate"><span class="pre">around</span></code></a>(a[,&nbsp;decimals,&nbsp;out])</p>
</td>
<td>
<p>Evenly round to the given number of decimals.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.round_" href="https://numpy.org/doc/stable/reference/generated/numpy.round_.html#numpy.round_"><code class="xref py py-obj docutils literal notranslate"><span class="pre">round_</span></code></a>(a[,&nbsp;decimals,&nbsp;out])</p>
</td>
<td>
<p>Round an array to the given number of decimals.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.rint" href="https://numpy.org/doc/stable/reference/generated/numpy.rint.html#numpy.rint"><code class="xref py py-obj docutils literal notranslate"><span class="pre">rint</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Round elements of the array to the nearest integer.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.fix" href="https://numpy.org/doc/stable/reference/generated/numpy.fix.html#numpy.fix"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fix</span></code></a>(x[,&nbsp;out])</p>
</td>
<td>
<p>Round to nearest integer towards zero.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.floor" href="https://numpy.org/doc/stable/reference/generated/numpy.floor.html#numpy.floor"><code class="xref py py-obj docutils literal notranslate"><span class="pre">floor</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the floor of the input, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.ceil" href="https://numpy.org/doc/stable/reference/generated/numpy.ceil.html#numpy.ceil"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ceil</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the ceiling of the input, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.trunc" href="https://numpy.org/doc/stable/reference/generated/numpy.trunc.html#numpy.trunc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">trunc</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the truncated value of the input, element-wise.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="sums-products-differences" class="section">
<h2>Sums, products, differences</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.prod" href="https://numpy.org/doc/stable/reference/generated/numpy.prod.html#numpy.prod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">prod</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the product of array elements over a given axis.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.sum" href="https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sum</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims,&nbsp;&hellip;])</p>
</td>
<td>
<p>Sum of array elements over a given axis.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.nanprod" href="https://numpy.org/doc/stable/reference/generated/numpy.nanprod.html#numpy.nanprod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nanprod</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims])</p>
</td>
<td>
<p>Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.nansum" href="https://numpy.org/doc/stable/reference/generated/numpy.nansum.html#numpy.nansum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nansum</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims])</p>
</td>
<td>
<p>Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.cumprod" href="https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html#numpy.cumprod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumprod</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out])</p>
</td>
<td>
<p>Return the cumulative product of elements along a given axis.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.cumsum" href="https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html#numpy.cumsum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumsum</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out])</p>
</td>
<td>
<p>Return the cumulative sum of the elements along a given axis.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.nancumprod" href="https://numpy.org/doc/stable/reference/generated/numpy.nancumprod.html#numpy.nancumprod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nancumprod</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out])</p>
</td>
<td>
<p>Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.nancumsum" href="https://numpy.org/doc/stable/reference/generated/numpy.nancumsum.html#numpy.nancumsum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nancumsum</span></code></a>(a[,&nbsp;axis,&nbsp;dtype,&nbsp;out])</p>
</td>
<td>
<p>Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.diff" href="https://numpy.org/doc/stable/reference/generated/numpy.diff.html#numpy.diff"><code class="xref py py-obj docutils literal notranslate"><span class="pre">diff</span></code></a>(a[,&nbsp;n,&nbsp;axis,&nbsp;prepend,&nbsp;append])</p>
</td>
<td>
<p>Calculate the n-th discrete difference along the given axis.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.ediff1d" href="https://numpy.org/doc/stable/reference/generated/numpy.ediff1d.html#numpy.ediff1d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ediff1d</span></code></a>(ary[,&nbsp;to_end,&nbsp;to_begin])</p>
</td>
<td>
<p>The differences between consecutive elements of an array.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.gradient" href="https://numpy.org/doc/stable/reference/generated/numpy.gradient.html#numpy.gradient"><code class="xref py py-obj docutils literal notranslate"><span class="pre">gradient</span></code></a>(f,&nbsp;\*varargs[,&nbsp;axis,&nbsp;edge_order])</p>
</td>
<td>
<p>Return the gradient of an N-dimensional array.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.cross" href="https://numpy.org/doc/stable/reference/generated/numpy.cross.html#numpy.cross"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cross</span></code></a>(a,&nbsp;b[,&nbsp;axisa,&nbsp;axisb,&nbsp;axisc,&nbsp;axis])</p>
</td>
<td>
<p>Return the cross product of two (arrays of) vectors.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.trapz" href="https://numpy.org/doc/stable/reference/generated/numpy.trapz.html#numpy.trapz"><code class="xref py py-obj docutils literal notranslate"><span class="pre">trapz</span></code></a>(y[,&nbsp;x,&nbsp;dx,&nbsp;axis])</p>
</td>
<td>
<p>Integrate along the given axis using the composite trapezoidal rule.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="exponents-and-logarithms" class="section">
<h2>Exponents and logarithms</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.exp" href="https://numpy.org/doc/stable/reference/generated/numpy.exp.html#numpy.exp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">exp</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Calculate the exponential of all elements in the input array.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.expm1" href="https://numpy.org/doc/stable/reference/generated/numpy.expm1.html#numpy.expm1"><code class="xref py py-obj docutils literal notranslate"><span class="pre">expm1</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Calculate&nbsp;<code class="docutils literal notranslate"><span class="pre">exp(x)</span>&nbsp;<span class="pre">-</span>&nbsp;<span class="pre">1</span></code>&nbsp;for all elements in the array.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.exp2" href="https://numpy.org/doc/stable/reference/generated/numpy.exp2.html#numpy.exp2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">exp2</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Calculate&nbsp;<em class="xref py py-obj">2**p</em>&nbsp;for all&nbsp;<em class="xref py py-obj">p</em>&nbsp;in the input array.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.log" href="https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Natural logarithm, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.log10" href="https://numpy.org/doc/stable/reference/generated/numpy.log10.html#numpy.log10"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log10</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the base 10 logarithm of the input array, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.log2" href="https://numpy.org/doc/stable/reference/generated/numpy.log2.html#numpy.log2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log2</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Base-2 logarithm of&nbsp;<em class="xref py py-obj">x</em>.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.log1p" href="https://numpy.org/doc/stable/reference/generated/numpy.log1p.html#numpy.log1p"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log1p</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the natural logarithm of one plus the input array, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.logaddexp" href="https://numpy.org/doc/stable/reference/generated/numpy.logaddexp.html#numpy.logaddexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logaddexp</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Logarithm of the sum of exponentiations of the inputs.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.logaddexp2" href="https://numpy.org/doc/stable/reference/generated/numpy.logaddexp2.html#numpy.logaddexp2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logaddexp2</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Logarithm of the sum of exponentiations of the inputs in base-2.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="other-special-functions" class="section">
<h2>Other special functions</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.i0" href="https://numpy.org/doc/stable/reference/generated/numpy.i0.html#numpy.i0"><code class="xref py py-obj docutils literal notranslate"><span class="pre">i0</span></code></a>(x)</p>
</td>
<td>
<p>Modified Bessel function of the first kind, order 0.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.sinc" href="https://numpy.org/doc/stable/reference/generated/numpy.sinc.html#numpy.sinc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sinc</span></code></a>(x)</p>
</td>
<td>
<p>Return the sinc function.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="floating-point-routines" class="section">
<h2>Floating point routines</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.signbit" href="https://numpy.org/doc/stable/reference/generated/numpy.signbit.html#numpy.signbit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">signbit</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns element-wise True where signbit is set (less than zero).</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.copysign" href="https://numpy.org/doc/stable/reference/generated/numpy.copysign.html#numpy.copysign"><code class="xref py py-obj docutils literal notranslate"><span class="pre">copysign</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Change the sign of x1 to that of x2, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.frexp" href="https://numpy.org/doc/stable/reference/generated/numpy.frexp.html#numpy.frexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">frexp</span></code></a>(x[,&nbsp;out1,&nbsp;out2],&nbsp;/&nbsp;[[,&nbsp;out,&nbsp;where,&nbsp;&hellip;])</p>
</td>
<td>
<p>Decompose the elements of x into mantissa and twos exponent.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.ldexp" href="https://numpy.org/doc/stable/reference/generated/numpy.ldexp.html#numpy.ldexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ldexp</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns x1 * 2**x2, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.nextafter" href="https://numpy.org/doc/stable/reference/generated/numpy.nextafter.html#numpy.nextafter"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nextafter</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the next floating-point value after x1 towards x2, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.spacing" href="https://numpy.org/doc/stable/reference/generated/numpy.spacing.html#numpy.spacing"><code class="xref py py-obj docutils literal notranslate"><span class="pre">spacing</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the distance between x and the nearest adjacent number.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="rational-routines" class="section">
<h2>Rational routines</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.lcm" href="https://numpy.org/doc/stable/reference/generated/numpy.lcm.html#numpy.lcm"><code class="xref py py-obj docutils literal notranslate"><span class="pre">lcm</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns the lowest common multiple of&nbsp;<code class="docutils literal notranslate"><span class="pre">|x1|</span></code>&nbsp;and&nbsp;<code class="docutils literal notranslate"><span class="pre">|x2|</span></code></p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.gcd" href="https://numpy.org/doc/stable/reference/generated/numpy.gcd.html#numpy.gcd"><code class="xref py py-obj docutils literal notranslate"><span class="pre">gcd</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns the greatest common divisor of&nbsp;<code class="docutils literal notranslate"><span class="pre">|x1|</span></code>&nbsp;and&nbsp;<code class="docutils literal notranslate"><span class="pre">|x2|</span></code></p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="arithmetic-operations" class="section">
<h2><span class="highlighted">Arithmetic</span>&nbsp;operations</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.add" href="https://numpy.org/doc/stable/reference/generated/numpy.add.html#numpy.add"><code class="xref py py-obj docutils literal notranslate"><span class="pre">add</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Add arguments element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.reciprocal" href="https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html#numpy.reciprocal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">reciprocal</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the reciprocal of the argument, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.positive" href="https://numpy.org/doc/stable/reference/generated/numpy.positive.html#numpy.positive"><code class="xref py py-obj docutils literal notranslate"><span class="pre">positive</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Numerical positive, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.negative" href="https://numpy.org/doc/stable/reference/generated/numpy.negative.html#numpy.negative"><code class="xref py py-obj docutils literal notranslate"><span class="pre">negative</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Numerical negative, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.multiply" href="https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy.multiply"><code class="xref py py-obj docutils literal notranslate"><span class="pre">multiply</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Multiply arguments element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.divide" href="https://numpy.org/doc/stable/reference/generated/numpy.divide.html#numpy.divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">divide</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns a true division of the inputs, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.power" href="https://numpy.org/doc/stable/reference/generated/numpy.power.html#numpy.power"><code class="xref py py-obj docutils literal notranslate"><span class="pre">power</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>First array elements raised to powers from second array, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.subtract" href="https://numpy.org/doc/stable/reference/generated/numpy.subtract.html#numpy.subtract"><code class="xref py py-obj docutils literal notranslate"><span class="pre">subtract</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Subtract arguments, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.true_divide" href="https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html#numpy.true_divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">true_divide</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns a true division of the inputs, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.floor_divide" href="https://numpy.org/doc/stable/reference/generated/numpy.floor_divide.html#numpy.floor_divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">floor_divide</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the largest integer smaller or equal to the division of the inputs.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.float_power" href="https://numpy.org/doc/stable/reference/generated/numpy.float_power.html#numpy.float_power"><code class="xref py py-obj docutils literal notranslate"><span class="pre">float_power</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;&hellip;])</p>
</td>
<td>
<p>First array elements raised to powers from second array, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.fmod" href="https://numpy.org/doc/stable/reference/generated/numpy.fmod.html#numpy.fmod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmod</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the element-wise remainder of division.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.mod" href="https://numpy.org/doc/stable/reference/generated/numpy.mod.html#numpy.mod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mod</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return element-wise remainder of division.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.modf" href="https://numpy.org/doc/stable/reference/generated/numpy.modf.html#numpy.modf"><code class="xref py py-obj docutils literal notranslate"><span class="pre">modf</span></code></a>(x[,&nbsp;out1,&nbsp;out2],&nbsp;/&nbsp;[[,&nbsp;out,&nbsp;where,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the fractional and integral parts of an array, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.remainder" href="https://numpy.org/doc/stable/reference/generated/numpy.remainder.html#numpy.remainder"><code class="xref py py-obj docutils literal notranslate"><span class="pre">remainder</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return element-wise remainder of division.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.divmod" href="https://numpy.org/doc/stable/reference/generated/numpy.divmod.html#numpy.divmod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">divmod</span></code></a>(x1,&nbsp;x2[,&nbsp;out1,&nbsp;out2],&nbsp;/&nbsp;[[,&nbsp;out,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return element-wise quotient and remainder simultaneously.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="handling-complex-numbers" class="section">
<h2>Handling complex numbers</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.angle" href="https://numpy.org/doc/stable/reference/generated/numpy.angle.html#numpy.angle"><code class="xref py py-obj docutils literal notranslate"><span class="pre">angle</span></code></a>(z[,&nbsp;deg])</p>
</td>
<td>
<p>Return the angle of the complex argument.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.real" href="https://numpy.org/doc/stable/reference/generated/numpy.real.html#numpy.real"><code class="xref py py-obj docutils literal notranslate"><span class="pre">real</span></code></a>(val)</p>
</td>
<td>
<p>Return the real part of the complex argument.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.imag" href="https://numpy.org/doc/stable/reference/generated/numpy.imag.html#numpy.imag"><code class="xref py py-obj docutils literal notranslate"><span class="pre">imag</span></code></a>(val)</p>
</td>
<td>
<p>Return the imaginary part of the complex argument.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.conj" href="https://numpy.org/doc/stable/reference/generated/numpy.conj.html#numpy.conj"><code class="xref py py-obj docutils literal notranslate"><span class="pre">conj</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the complex conjugate, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.conjugate" href="https://numpy.org/doc/stable/reference/generated/numpy.conjugate.html#numpy.conjugate"><code class="xref py py-obj docutils literal notranslate"><span class="pre">conjugate</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the complex conjugate, element-wise.</p>
</td>
</tr>
</tbody>
</table>
</div>
<div id="miscellaneous" class="section">
<h2>Miscellaneous</h2>
<table class="longtable docutils align-default"><colgroup><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.convolve" href="https://numpy.org/doc/stable/reference/generated/numpy.convolve.html#numpy.convolve"><code class="xref py py-obj docutils literal notranslate"><span class="pre">convolve</span></code></a>(a,&nbsp;v[,&nbsp;mode])</p>
</td>
<td>
<p>Returns the discrete, linear convolution of two one-dimensional sequences.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.clip" href="https://numpy.org/doc/stable/reference/generated/numpy.clip.html#numpy.clip"><code class="xref py py-obj docutils literal notranslate"><span class="pre">clip</span></code></a>(a,&nbsp;a_min,&nbsp;a_max[,&nbsp;out])</p>
</td>
<td>
<p>Clip (limit) the values in an array.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.sqrt" href="https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html#numpy.sqrt"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sqrt</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the non-negative square-root of an array, element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.cbrt" href="https://numpy.org/doc/stable/reference/generated/numpy.cbrt.html#numpy.cbrt"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cbrt</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the cube-root of an array, element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.square" href="https://numpy.org/doc/stable/reference/generated/numpy.square.html#numpy.square"><code class="xref py py-obj docutils literal notranslate"><span class="pre">square</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Return the element-wise square of the input.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.absolute" href="https://numpy.org/doc/stable/reference/generated/numpy.absolute.html#numpy.absolute"><code class="xref py py-obj docutils literal notranslate"><span class="pre">absolute</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Calculate the absolute value element-wise.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.fabs" href="https://numpy.org/doc/stable/reference/generated/numpy.fabs.html#numpy.fabs"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fabs</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Compute the absolute values element-wise.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.sign" href="https://numpy.org/doc/stable/reference/generated/numpy.sign.html#numpy.sign"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sign</span></code></a>(x,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;order,&nbsp;&hellip;])</p>
</td>
<td>
<p>Returns an element-wise indication of the sign of a number.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.heaviside" href="https://numpy.org/doc/stable/reference/generated/numpy.heaviside.html#numpy.heaviside"><code class="xref py py-obj docutils literal notranslate"><span class="pre">heaviside</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Compute the Heaviside step function.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.maximum" href="https://numpy.org/doc/stable/reference/generated/numpy.maximum.html#numpy.maximum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">maximum</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Element-wise maximum of array elements.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.minimum" href="https://numpy.org/doc/stable/reference/generated/numpy.minimum.html#numpy.minimum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">minimum</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Element-wise minimum of array elements.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.fmax" href="https://numpy.org/doc/stable/reference/generated/numpy.fmax.html#numpy.fmax"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmax</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Element-wise maximum of array elements.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.fmin" href="https://numpy.org/doc/stable/reference/generated/numpy.fmin.html#numpy.fmin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmin</span></code></a>(x1,&nbsp;x2,&nbsp;/[,&nbsp;out,&nbsp;where,&nbsp;casting,&nbsp;&hellip;])</p>
</td>
<td>
<p>Element-wise minimum of array elements.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.nan_to_num" href="https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html#numpy.nan_to_num"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nan_to_num</span></code></a>(x[,&nbsp;copy,&nbsp;nan,&nbsp;posinf,&nbsp;neginf])</p>
</td>
<td>
<p>Replace NaN with zero and infinity with large finite numbers (default behaviour) or with the numbers defined by the user using the&nbsp;<a class="reference internal" title="numpy.nan" href="https://numpy.org/doc/stable/reference/constants.html#numpy.nan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nan</span></code></a>,&nbsp;<em class="xref py py-obj">posinf</em>&nbsp;and/or&nbsp;<em class="xref py py-obj">neginf</em>&nbsp;keywords.</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p><a class="reference internal" title="numpy.real_if_close" href="https://numpy.org/doc/stable/reference/generated/numpy.real_if_close.html#numpy.real_if_close"><code class="xref py py-obj docutils literal notranslate"><span class="pre">real_if_close</span></code></a>(a[,&nbsp;tol])</p>
</td>
<td>
<p>If input is complex with all imaginary parts close to zero, return real parts.</p>
</td>
</tr>
<tr class="row-even">
<td>
<p><a class="reference internal" title="numpy.interp" href="https://numpy.org/doc/stable/reference/generated/numpy.interp.html#numpy.interp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">interp</span></code></a>(x,&nbsp;xp,&nbsp;fp[,&nbsp;left,&nbsp;right,&nbsp;period])</p>
</td>
<td>
<p>One-dimensional linear interpolation.</p>
</td>
</tr>
</tbody>
</table>
</div>

<h1>Array Broadcasting in Numpy</h1>
<p>Let&rsquo;s explore a more advanced concept in numpy called broadcasting. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is &ldquo;broadcast&rdquo; across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. This article provides a gentle introduction to broadcasting with numerous examples ranging from simple to involved. It also provides hints on when and when not to use broadcasting.</p>
<p>numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape:</p>
<div id="example-1" class="literal-block-wrapper docutils container">
<div class="code-block-caption"><span class="caption-text">Example 1</span></div>
<div class="highlight-python notranslate">
<div class="highlight"><span class="copybutton" title="Hide the prompts and output">&gt;&gt;&gt;</span>
<pre><span class="gp">&gt;&gt;&gt; </span><span class="kn">from</span> <span class="nn">numpy</span> <span class="kn">import</span> <span class="n">array</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">b</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">2.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">*</span> <span class="n">b</span>
<span class="go">array([ 2.,  4.,  6.])</span>
</pre>
</div>
</div>
</div>
<p>numpy&rsquo;s broadcasting rule relaxes this constraint when the arrays&rsquo; shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:</p>
<div id="example-2" class="literal-block-wrapper docutils container">
<div class="code-block-caption"><span class="caption-text">Example 2</span></div>
<div class="highlight-python notranslate">
<div class="highlight"><span class="copybutton" title="Hide the prompts and output">&gt;&gt;&gt;</span>
<pre><span class="gp">&gt;&gt;&gt; </span><span class="kn">from</span> <span class="nn">numpy</span> <span class="kn">import</span> <span class="n">array</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span><span class="mf">2.0</span><span class="p">,</span><span class="mf">3.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">b</span> <span class="o">=</span> <span class="mf">2.0</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">*</span> <span class="n">b</span>
<span class="go">array([ 2.,  4.,  6.])</span>
</pre>
</div>
</div>
</div>
<p>The result is equivalent to the previous example where&nbsp;<code class="docutils literal notranslate"><span class="pre">b</span></code>&nbsp;was an array. We can think of the scalar&nbsp;<code class="docutils literal notranslate"><span class="pre">b</span></code>&nbsp;being stretched during the arithmetic operation into an array with the same shape as&nbsp;<code class="docutils literal notranslate"><span class="pre">a</span></code>. The new elements in&nbsp;<code class="docutils literal notranslate"><span class="pre">b</span></code>, as shown in&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#figure-1"><span class="std std-ref">Figure 1</span></a>, are simply copies of the original scalar. The stretching analogy is only conceptual. numpy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible. Because&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#example-2"><span class="std std-ref">Example 2</span></a>&nbsp;moves less memory, (<code class="docutils literal notranslate"><span class="pre">b</span></code>&nbsp;is a scalar, not an array) around during the multiplication, it is about 10% faster than&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#example-1"><span class="std std-ref">Example 1</span></a>&nbsp;using the standard numpy on Windows 2000 with one million element arrays.</p>
<div id="figure-1" class="figure align-default"><img src="https://numpy.org/doc/stable/_images/theory.broadcast_1.gif" alt="Vector-Scalar multiplication" />
<p class="caption"><span class="caption-text"><em>Figure 1</em></span></p>
<div class="legend">
<p><em>In the simplest example of broadcasting, the scalar ``b`` is stretched to become an array of with the same shape as ``a`` so the shapes are compatible for element-by-element multiplication.</em></p>
</div>
</div>
<p>The rule governing whether two arrays have compatible shapes for broadcasting can be expressed in a single sentence.</p>
<div class="admonition-the-broadcasting-rule admonition">
<p class="admonition-title">The Broadcasting Rule</p>
<p><strong>In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.</strong></p>
</div>
<p>If this condition is not met, a&nbsp;<code class="docutils literal notranslate"><span class="pre">ValueError('frames</span>&nbsp;<span class="pre">are</span>&nbsp;<span class="pre">not</span>&nbsp;<span class="pre">aligned')</span></code>&nbsp;exception is thrown indicating that the arrays have incompatible shapes. The size of the result array created by broadcast operations is the maximum size along each dimension from the input arrays. Note that the rule does not say anything about the two arrays needing to have the same number of dimensions. So, for example, if you have a 256 x 256 x 3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rule shows that they are compatible</p>
<table class="docutils align-default"><colgroup><col /><col /><col /><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p>Image</p>
</td>
<td>
<p>(3d array)</p>
</td>
<td>
<p>256 x</p>
</td>
<td>
<p>256 x</p>
</td>
<td>
<p>3</p>
</td>
</tr>
<tr class="row-even">
<td>
<p>Scale</p>
</td>
<td>
<p>(1d array)</p>
</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>
<p>3</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p>Result</p>
</td>
<td>
<p>(3d array)</p>
</td>
<td>
<p>256 x</p>
</td>
<td>
<p>256 x</p>
</td>
<td>
<p>3</p>
</td>
</tr>
</tbody>
</table>
<p>In the following example, both the&nbsp;<code class="docutils literal notranslate"><span class="pre">A</span></code>&nbsp;and&nbsp;<code class="docutils literal notranslate"><span class="pre">B</span></code>&nbsp;arrays have axes with length one that are expanded to a larger size in a broadcast operation.</p>
<table class="docutils align-default"><colgroup><col /><col /><col /><col /><col /><col /></colgroup>
<tbody>
<tr class="row-odd">
<td>
<p>A</p>
</td>
<td>
<p>(4d array)</p>
</td>
<td>
<p>8 x</p>
</td>
<td>
<p>1 x</p>
</td>
<td>
<p>6 x</p>
</td>
<td>
<p>1</p>
</td>
</tr>
<tr class="row-even">
<td>
<p>B</p>
</td>
<td>
<p>(3d array)</p>
</td>
<td>&nbsp;</td>
<td>
<p>7 x</p>
</td>
<td>
<p>1 x</p>
</td>
<td>
<p>5</p>
</td>
</tr>
<tr class="row-odd">
<td>
<p>Result</p>
</td>
<td>
<p>(4d array)</p>
</td>
<td>
<p>8 x</p>
</td>
<td>
<p>7 x</p>
</td>
<td>
<p>6 x</p>
</td>
<td>
<p>5</p>
</td>
</tr>
</tbody>
</table>
<p>Below, are several code examples and graphical representations that help make the broadcast rule visually obvious.&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#example-3"><span class="std std-ref">Example 3</span></a>&nbsp;adds a one-dimensional array to a two-dimensional array:</p>
<div id="example-3" class="literal-block-wrapper docutils container">
<div class="code-block-caption"><span class="caption-text">Example 3</span></div>
<div class="highlight-python notranslate">
<div class="highlight"><span class="copybutton" title="Hide the prompts and output">&gt;&gt;&gt;</span>
<pre><span class="gp">&gt;&gt;&gt; </span><span class="kn">from</span> <span class="nn">numpy</span> <span class="kn">import</span> <span class="n">array</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">=</span> <span class="n">array</span><span class="p">([[</span> <span class="mf">0.0</span><span class="p">,</span>  <span class="mf">0.0</span><span class="p">,</span>  <span class="mf">0.0</span><span class="p">],</span>
<span class="gp">... </span>           <span class="p">[</span><span class="mf">10.0</span><span class="p">,</span> <span class="mf">10.0</span><span class="p">,</span> <span class="mf">10.0</span><span class="p">],</span>
<span class="gp">... </span>           <span class="p">[</span><span class="mf">20.0</span><span class="p">,</span> <span class="mf">20.0</span><span class="p">,</span> <span class="mf">20.0</span><span class="p">],</span>
<span class="gp">... </span>           <span class="p">[</span><span class="mf">30.0</span><span class="p">,</span> <span class="mf">30.0</span><span class="p">,</span> <span class="mf">30.0</span><span class="p">]])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">b</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">+</span> <span class="n">b</span>
<span class="go">array([[  1.,   2.,   3.],</span>
<span class="go">       [ 11.,  12.,  13.],</span>
<span class="go">       [ 21.,  22.,  23.],</span>
<span class="go">       [ 31.,  32.,  33.]])</span>
</pre>
</div>
</div>
</div>
<p>As shown in&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#figure-2"><span class="std std-ref">Figure 2</span></a>,&nbsp;<code class="docutils literal notranslate"><span class="pre">b</span></code>&nbsp;is added to each row of&nbsp;<code class="docutils literal notranslate"><span class="pre">a</span></code>. When&nbsp;<code class="docutils literal notranslate"><span class="pre">b</span></code>&nbsp;is longer than the rows of&nbsp;<code class="docutils literal notranslate"><span class="pre">a</span></code>, as in&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#figure-3"><span class="std std-ref">Figure 3</span></a>, an exception is raised because of the incompatible shapes.</p>
<div id="figure-2" class="figure align-default"><img src="https://numpy.org/doc/stable/_images/theory.broadcast_2.gif" alt="Matrix-Vector" />
<p class="caption"><span class="caption-text"><em>Figure 2</em></span></p>
<div class="legend">
<p><em>A two dimensional array multiplied by a one dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.</em></p>
</div>
</div>
<div id="figure-3" class="figure align-default"><img src="https://numpy.org/doc/stable/_images/theory.broadcast_3.gif" alt="Matrix-Vector-with-error" />
<p class="caption"><span class="caption-text"><em>Figure 3</em></span></p>
<div class="legend">
<p><em>When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.</em></p>
</div>
</div>
<p>Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays that produces the same result as&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#example-3"><span class="std std-ref">Example 3</span></a></p>
<div id="example-4" class="literal-block-wrapper docutils container">
<div class="code-block-caption"><span class="caption-text">Example 4</span></div>
<div class="highlight-python notranslate">
<div class="highlight"><span class="copybutton" title="Hide the prompts and output">&gt;&gt;&gt;</span>
<pre><span class="gp">&gt;&gt;&gt; </span><span class="kn">from</span> <span class="nn">numpy</span> <span class="kn">import</span> <span class="n">array</span><span class="p">,</span> <span class="n">newaxis</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">0.0</span><span class="p">,</span> <span class="mf">10.0</span><span class="p">,</span> <span class="mf">20.0</span><span class="p">,</span> <span class="mf">30.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">b</span> <span class="o">=</span> <span class="n">array</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span><span class="p">[:,</span><span class="n">newaxis</span><span class="p">]</span> <span class="o">+</span> <span class="n">b</span>
<span class="go">array([[  1.,   2.,   3.],</span>
<span class="go">       [ 11.,  12.,  13.],</span>
<span class="go">       [ 21.,  22.,  23.],</span>
<span class="go">       [ 31.,  32.,  33.]])</span>
</pre>
</div>
</div>
</div>
<p>Here the newaxis index operator inserts a new axis into&nbsp;<code class="docutils literal notranslate"><span class="pre">a</span></code>, making it a two-dimensional 4x1 array.&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#figure-4"><span class="std std-ref">Figure 4</span></a>&nbsp;illustrates the stretching of both arrays to produce the desired 4x3 output array.</p>
<div id="figure-4" class="figure align-default"><img src="https://numpy.org/doc/stable/_images/theory.broadcast_4.gif" alt="vector-vector with newaxis" />
<p class="caption"><span class="caption-text"><em>Figure 4</em></span></p>
<div class="legend">
<p>In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.*</p>
</div>
</div>
<div id="a-practical-example-vector-quantization" class="section">
<h2>A Practical Example: Vector Quantization.</h2>
<p>Broadcasting comes up quite often in real world problems. A typical example occurs in the vector quantization (VQ) algorithm used in information theory, classification, and other related areas. The basic operation in VQ [#f0] finds the closest point in a set of points, called codes in VQ jargon, to a given point, called the observation. In the very simple, two-dimensional case shown in&nbsp;<a class="reference internal" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#figure-5"><span class="std std-ref">Figure 5</span></a>, the values in observation describe the weight and height of an athlete to be classified. The codes represent different classes of athletes.&nbsp;<a id="id2" class="footnote-reference brackets" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#f1">2</a>&nbsp;Finding the closest point requires calculating the distance between observation and each of the codes. The shortest distance provides the best match. In this example,&nbsp;<code class="docutils literal notranslate"><span class="pre">codes[0]</span></code>&nbsp;is the closest class indicating that the athlete is likely a basketball player.</p>
<div id="figure-5" class="figure align-default"><img src="https://numpy.org/doc/stable/_images/theory.broadcast_5.png" alt="vector quantitization example" />
<p class="caption"><span class="caption-text"><em>Figure 5</em></span></p>
<div class="legend">
<p><em>The basic operation of vector quantization calculates the distance between an object to be classified, the dark square, and multiple known codes, the gray circles. In this simple case, the codes represent individual classes. More complex cases use multiple codes per class.</em></p>
</div>
</div>
<p class="rubric">Footnotes</p>
<dl class="footnote brackets">
<dt id="f0" class="label"><span class="brackets">1</span></dt>
<dd>
<p>Vector Quantization J. Makhoul, S. Roucos, and H. Gish, &ldquo;Vector Quantization in Speech Coding,&rdquo; Proc. IEEE, vol. 73, pp. 1551-1587, Nov. 1985.</p>
</dd>
<dt id="f1" class="label"><span class="brackets"><a class="fn-backref" href="https://numpy.org/doc/stable/user/theory.broadcasting.html#id2">2</a></span></dt>
<dd>
<p>In this example, weight has more impact on the distance calculation than height because of the larger values. In practice, it is important to normalize the height and weight, often by their standard deviation across the data set, so that both have equal influence on the distance calculation.</p>
</dd>
</dl>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The code to produce the figures is part of the&nbsp;<a class="reference external" href="http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html">AstroML book</a></p>
</div>
</div>

![](https://hackster.imgix.net/uploads/attachments/1072845/untitled_drawing_cpdJbD4KkR.png?auto=compress%2Cformat&w=1280&h=960&fit=max)